---
rust:
  directory: ../../
  manifestPath: filen-sdk-rs/Cargo.toml

android:
  cargoExtras: ['--features', 'uniffi,heif-decoder']
  targets:
    - arm64-v8a
    - x86_64
  useSharedLibrary: true

ios:
  cargoExtras: ['--features', 'uniffi,heif-decoder']
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
