[build]
rustflags = ["-Zhigher-ranked-assumptions"]

[target.wasm32-unknown-unknown]
rustflags = [
	"-C",
	"target-feature=-nontrapping-fptoint,+atomics,+bulk-memory",
	"--cfg",
	"getrandom_backend=\"wasm_js\"",
]

[target.x86_64-pc-windows-msvc]
rustflags = ["-Zhigher-ranked-assumptions", "-C", "link-arg=/STACK:2097152"]

# 64 bit Mingw
[target.x86_64-pc-windows-gnu]
rustflags = [
	"-Zhigher-ranked-assumptions",
	"-C",
	"link-arg=-Wl,--stack,2097152",
]
