[package]
name = "uniffi-bindgen-swift"
version = "0.1.0"
edition = "2024"

[dependencies]
uniffi = { version = "0.29.4", features = ["cli"] }

[[bin]]
name = "uniffi-bindgen-swift"
path = "uniffi-bindgen-swift.rs"
