[package]
name = "anchored-ref"
version = "0.1.0"
edition = "2024"

[features]
default = []
nightly = []

[dependencies]
filen-macros = { path = "../filen-macros" }

[dev-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
bytes = "1.10.1"
serde_json = "1.0.143"
