name: Publish to npm

on:
  push:
    tags:
      - 'filen-js@*'
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: 'npm'
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-08-14
          targets: wasm32-unknown-unknown, aarch64-linux-android, x86_64-linux-android, aarch64-apple-ios, aarch64-apple-ios-sim
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        with:
          sdk-version: 36
          build-tools-version: 35.0.0
          cmake-version: 3.10.2.4988404
          ndk-version: 27.0.12077973
      - uses: Swatinem/rust-cache@v2
        with:
          key: cargo-build-release-js
          add-rust-environment-hash-key: 'false'
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          # waiting on a new release that includes
          # https://github.com/drager/wasm-pack/pull/1428
          tool: wasm-pack
          git: https://github.com/drager/wasm-pack
          rev: cd1718aa7babb656796b8aae3c177ddacce28028
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          # Can't use the latest version until https://github.com/bbqsrc/cargo-ndk/issues/181 is resolved
          tool: cargo-ndk@3.5.4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Build WASM bundle
        run: sh wasm-pack.sh
        working-directory: ./filen-sdk-rs
      - name: Install dependencies
        run: npm install --package-lock-only && npm ci
        working-directory: ./filen-sdk-rs/web
      - name: Build React Native Bundle
        run: npm run ubrn:release
        working-directory: ./filen-sdk-rs/web
      - name: Configure npm for publishing
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ~/.npmrc
      - name: Publish
        run: npm publish --access public
        working-directory: ./filen-sdk-rs/web
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Cleanup
        run: rm -rf ~/.npmrc
